name : 'Generate and Update README'
description : 'Using github actions for generating and updating README.md file'
author: 'KanishkChhajed'
# branding:
#     icon: 'book'
#     color: 'gray-dark'
inputs:
  # template-path:
    # description: 'Path to template file'
    # required: false
    # default: 'temp/Readme_template.ejs'
  # output-path:
    # description: 'Path to output readme file'
    # required: false
    # default: 'README.md'

  token:
    description: 'Github token for accessing repository contents'
    required : false
    default : github.token

runs:
  using: 'node20'
  main: 'src/main.js'


