name: 'Generate a readme file for a repo'
on:
    workflow_dispatch:
    push:
        branches:
            - 'main'
        paths-ignore:
            - '**.md'
            - '.github/workflows/*'
    # schedule:
        # - cron : '0 * * * *'   #Run every hour

permissions:
    contents: write
    # models: read

env:
    SECRET: ${{secrets.GITHUB_TOKEN}}
    # GITHUB_CONTEXT: ${{ toJson(github) }}

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name : My first job
              run : |
                 echo "Hello World!!!"
                #  echo $GITHUB_CONTEXT

    second_job:
        runs-on: ubuntu-latest
        steps:
            - name: Install Node on image machine
              run : npm install node@latest
            - name : Checkout my repository
              uses : actions/checkout@v4
              with :
                repository : github.repository

            - name : Initalize my build action
              uses : ./.git-readme-action/action.yml@main
              with :
                environment_variable : ${{secrets.GITHUB_TOKEN}} 